version: "3"
services:
        db:
            image: postgres
            environment:
                POSTGRES_PASSWORD: password123
                POSTGRES_USER: user123
                POSTGRES_DB: db123
        app:
            image: ochanthou/m-compose:0.0.1
            ports:
                - 13000:3000